In [224]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime

In [225]:
FILENAME = 'cab_rides.csv'
df = pd.read_csv(FILENAME)

In [226]:
#Changing time Stamp to date and time
df['time_stamp'] = pd.to_datetime(df['time_stamp'], unit='ms').dt.time

In [227]:
df

,distance,cab_type,time_stamp,destination,source,price,surge_multiplier,id,product_id,name
0,0.44,Lyft,09:30:07.890000,North Station,Haymarket Square,5.0,1.0,424553bb-7174-41ea-aeb4-fe06d4f4b9d7,lyft_line,Shared
1,0.44,Lyft,02:00:23.677000,North Station,Haymarket Square,11.0,1.0,4bd23055-6827-41c6-b23b-3c491f24e74d,lyft_premier,Lux
2,0.44,Lyft,01:00:22.198000,North Station,Haymarket Square,7.0,1.0,981a3613-77af-4620-a42a-0c0866077d1e,lyft,Lyft
3,0.44,Lyft,04:53:02.749000,North Station,Haymarket Square,26.0,1.0,c2d88af2-d278-4bfd-a8d0-29ca77cc5512,lyft_luxsuv,Lux Black XL
4,0.44,Lyft,03:49:20.223000,North Station,Haymarket Square,9.0,1.0,e0126e1f-8ca9-4f2e-82b3-50505a09db9a,lyft_plus,Lyft XL
...,...,...,...,...,...,...,...,...,...,...
693066,1.00,Uber,23:53:05.534000,North End,West End,13.0,1.0,616d3611-1820-450a-9845-a9ff304a4842,6f72dfc5-27f1-42e8-84db-ccc7a75f6969,UberXL
693067,1.00,Uber,23:53:05.534000,North End,West End,9.5,1.0,633a3fc3-1f86-4b9e-9d48-2b7132112341,55c66225-fbe7-4fd5-9072-eab1ece5e23e,UberX
693068,1.00,Uber,23:53:05.534000,North End,West End,NaN,1.0,64d451d0-639f-47a4-9b7c-6fd92fbd264f,8cf7e821-f0d3-49c6-8eba-e679c0ebcf6a,Taxi
693069,1.00,Uber,23:53:05.534000,North End,West End,27.0,1.0,727e5f07-a96b-4ad1-a2c7-9abc3ad55b4e,6d318bcc-22a3-4af6-bddd-b409bfce1546,Black SUV
693070,1.00,Uber,23:53:05.534000,North End,West End,10.0,1.0,e7fdc087-fe86-40a5-a3c3-3b2a8badcbda,997acbb5-e102-41e1-b155-9df7de0a73f2,UberPool

In [228]:
#sorting the uber and Lyft rides
df_1 = df.loc[df['cab_type']=='Uber']
df_2 = df.loc[df['cab_type']=="Lyft"]

In [229]:
# Sorting distance of both the datasets
#Uber
distances_Uber = (df_1.distance)
distances_Uber_unique = sorted(df_1.distance.unique())
#Lyft
distances_Lyft = (df_2.distance)
distances_Lyft_unique = sorted(df_2.distance.unique())

#Prices
#Uber
price_Uber = (df_1.price)
#Lyft
price_Lyft = (df_2.price)

#time
#Uber
time_Uber = (df_1.time_stamp)
#Lyft
time_Lyft = (df_2.time_stamp)

In [230]:
### Uber Dataframe sorted by time
Dict_Uber = {'Distance':distances_Uber,'Price':price_Uber,'Time':time_Uber}
df_Uber1 = pd.DataFrame(Dict_Uber)
df_Uber = df_Uber1.sort_values('Time').dropna()
df_Uber

        Distance  Price             Time
370823      2.17   15.0  00:00:03.400000
50714       2.46   30.5  00:00:03.400000
370824      2.17   22.0  00:00:03.400000
370820      2.17   15.0  00:00:03.400000
370821      2.17   29.0  00:00:03.400000
...          ...    ...              ...
493914      1.00    8.5  23:59:08.312000
598295      1.24   27.0  23:59:08.316000
95599       1.56   26.5  23:59:08.316000
598297      1.24    7.0  23:59:08.316000
598296      1.24   11.0  23:59:08.316000

[330568 rows x 3 columns]

In [231]:
###LYFT DataFrame sorted by time
Dict_Lyft = {'Distance':distances_Lyft,'Price':price_Lyft,'Time':time_Lyft}
df_Lyft1 = pd.DataFrame(Dict_Lyft)
df_Lyft = df_Lyft1.sort_values('Time').dropna()
df_Lyft

        Distance  Price             Time
309007      2.53   19.5  00:00:03.539000
309008      2.53   22.5  00:00:03.539000
38517       2.54    3.0  00:00:03.539000
523736      1.36    7.0  00:00:03.618000
523738      1.36   13.5  00:00:03.618000
...          ...    ...              ...
493915      2.75   11.0  23:59:08.312000
75106       2.42   16.5  23:59:08.312000
493916      2.75   16.5  23:59:08.312000
598293      1.37    7.0  23:59:08.316000
598294      1.37   13.5  23:59:08.316000

[307408 rows x 3 columns]

In [232]:
#Uber distance and prices and time list
Uber_distance = df_Uber.Distance.tolist()
Uber_price = df_Uber.Price.tolist()
u_time = df_Uber.Time.tolist()

In [233]:
#Lyft distance and prices and time list
Lyft_distance = df_Lyft.Distance.tolist()
Lyft_price = df_Lyft.Price.tolist()
l_time = df_Lyft.Time.tolist()

In [234]:
#Converting Uber time to string and dividing the time periods into 4 parts
Uber_time =[]
for i in range(len(u_time)):
    v = u_time[i].strftime("%H:%M:%S")
    Uber_time.append(v)

Uber_00to06 = []
Uber_06to12 = []
Uber_12to18 = []
Uber_18to00 = []
Uber_00to06_price = []
Uber_06to12_price = []
Uber_12to18_price = []
Uber_18to00_price = []
Uber_00to06_distance = []
Uber_06to12_distance = []
Uber_12to18_distance = []
Uber_18to00_distance = []


for i in range(len(Uber_time)):
    if('00:00:00'<= Uber_time[i]<'06:00:00'):
        Uber_00to06.append(Uber_time[i])
        Uber_00to06_price.append(Uber_price[i])
        Uber_00to06_distance.append(Uber_distance[i])
    if('06:00:00'<= Uber_time[i]<'12:00:00'):
        Uber_06to12.append(Uber_time[i])
        Uber_06to12_price.append(Uber_price[i])
        Uber_06to12_distance.append(Uber_distance[i])
    if('12:00:00'<= Uber_time[i]<'18:00:00'):
        Uber_12to18.append(Uber_time[i])
        Uber_12to18_price.append(Uber_price[i])
        Uber_12to18_distance.append(Uber_distance[i])
    if('18:00:00'<= Uber_time[i]<='23:59:59'):
        Uber_18to00.append(Uber_time[i])
        Uber_18to00_price.append(Uber_price[i])
        Uber_18to00_distance.append(Uber_distance[i])

#Converting Lyft time to string and dividing the time periods into 4 parts

Lyft_time =[]
for i in range(len(l_time)):
    c = l_time[i].strftime("%H:%M:%S")
    Lyft_time.append(c)

Lyft_00to06 = []
Lyft_06to12 = []
Lyft_12to18 = []
Lyft_18to00 = []
Lyft_00to06_price = []
Lyft_06to12_price = []
Lyft_12to18_price = []
Lyft_18to00_price = []
Lyft_00to06_distance = []
Lyft_06to12_distance = []
Lyft_12to18_distance = []
Lyft_18to00_distance = []

for i in range(len(Lyft_time)):
    if('00:00:00'<= Lyft_time[i]<'06:00:00'):
        Lyft_00to06.append(Lyft_time[i])
        Lyft_00to06_price.append(Lyft_price[i])
        Lyft_00to06_distance.append(Lyft_distance[i])
    if('06:00:00'<= Lyft_time[i]<'12:00:00'):
        Lyft_06to12.append(Lyft_time[i])
        Lyft_06to12_price.append(Lyft_price[i])
        Lyft_06to12_distance.append(Lyft_distance[i])
    if('12:00:00'<= Lyft_time[i]<'18:00:00'):
        Lyft_12to18.append(Lyft_time[i])
        Lyft_12to18_price.append(Lyft_price[i])
        Lyft_12to18_distance.append(Lyft_distance[i])
    if('18:00:00'<= Lyft_time[i]<='23:59:59'):
        Lyft_18to00.append(Lyft_time[i])
        Lyft_18to00_price.append(Lyft_price[i])
        Lyft_18to00_distance.append(Lyft_distance[i])

In [235]:
### Uber for time period 1 Dataframe sorted by time
Dict_Uber1 = {'Distance':Uber_00to06_distance,'Price':Uber_00to06_price,'Time':Uber_00to06}
df_Uber1 = pd.DataFrame(Dict_Uber1)
df_Uber1 = df_Uber1.sort_values('Distance').dropna()

d_u1 = df_Uber1.Distance.tolist()
u1_05 = []
u1_1 = []
u1_15 = []
u1_2 = []
u1_25 = []
u1_3 = []
u1_35 = []
u1_4 = []
u1_45 = []
u1_5 = []
u1_55 = []
u1_6 = []
u1_65 = []
u1_7 = []
u1_75 = []
u1_8 = []

for i in range(len(d_u1)):
    if(d_u1[i]<=0.5):
        u1_05.append(d_u1[i])
    if(0.5<d_u1[i]<=1.0):
        u1_1.append(d_u1[i])
    if(1.0<d_u1[i]<=1.5):
        u1_15.append(d_u1[i])
    if(1.5<d_u1[i]<=2):
        u1_2.append(d_u1[i])
    if(2<d_u1[i]<=2.5):
        u1_25.append(d_u1[i])
    if(2.5<d_u1[i]<=3.0):
        u1_3.append(d_u1[i])
    if(3.0<d_u1[i]<=3.5):
        u1_35.append(d_u1[i])
    if(3.5<d_u1[i]<=4.0):
        u1_4.append(d_u1[i])
    if(4<d_u1[i]<=4.5):
        u1_45.append(d_u1[i])
    if(4.5<d_u1[i]<=5.0):
        u1_5.append(d_u1[i])
    if(5.0<d_u1[i]<=5.5):
        u1_55.append(d_u1[i])
    if(5.5<d_u1[i]<=6.0):
        u1_6.append(d_u1[i])
    if(6.0<d_u1[i]<=6.5):
        u1_65.append(d_u1[i])
    if(6.5<d_u1[i]<=7.0):
        u1_7.append(d_u1[i])
    if(7.0<d_u1[i]<=7.5):
        u1_75.append(d_u1[i])
    if(7.5<d_u1[i]<=8.0):
        u1_8.append(d_u1[i])

In [236]:


### Uber for time period 2 Dataframe sorted by time
Dict_Uber2 = {'Distance':Uber_06to12_distance,'Price':Uber_06to12_price,'Time':Uber_06to12}
df_Uber2 = pd.DataFrame(Dict_Uber2)
df_Uber2 = df_Uber2.sort_values('Distance').dropna()
df_Uber2

       Distance  Price      Time
78389      0.02    7.5  11:54:22
56542      0.02    6.5  10:23:07
78388      0.02    9.5  11:54:22
11194      0.02    6.5  06:49:50
56541      0.02   15.0  10:23:07
...         ...    ...       ...
19871      7.50   14.5  07:33:00
69147      7.50   46.0  11:15:22
57680      7.50   31.5  10:28:02
27617      7.50   16.5  08:12:21
27619      7.50   26.0  08:12:21

[79647 rows x 3 columns]

In [237]:
### Uber for time period 3 Dataframe sorted by time
Dict_Uber3 = {'Distance':Uber_12to18_distance,'Price':Uber_12to18_price,'Time':Uber_12to18}
df_Uber3 = pd.DataFrame(Dict_Uber3)
df_Uber3 = df_Uber3.sort_values('Distance').dropna()
df_Uber3

       Distance  Price      Time
64476      0.02   15.0  16:25:11
37532      0.02    8.5  14:35:07
39589      0.02   27.5  14:43:03
702        0.02   27.5  12:02:11
64475      0.02    6.5  16:25:11
...         ...    ...       ...
19396      7.62   17.0  13:20:06
28176      7.62   13.5  13:56:08
19397      7.62   28.5  13:20:06
60682      7.86   17.5  16:10:10
60681      7.86   36.0  16:10:10

[86847 rows x 3 columns]

In [238]:
### Uber for time period 4 Dataframe sorted by time
Dict_Uber4 = {'Distance':Uber_18to00_distance,'Price':Uber_18to00_price,'Time':Uber_18to00}
df_Uber4 = pd.DataFrame(Dict_Uber4)
df_Uber4 = df_Uber4.sort_values('Distance').dropna()
df_Uber4

       Distance  Price      Time
56631      0.02    6.5  22:13:07
52893      0.02   27.5  21:56:10
52892      0.02    8.5  21:56:10
72269      0.02   27.5  23:18:27
9205       0.02   15.0  18:37:57
...         ...    ...       ...
62483      7.46   54.0  22:40:03
23310      7.46   16.0  19:39:23
47061      7.46   16.0  21:30:10
23292      7.46   13.0  19:39:22
46322      7.50   18.5  21:27:24

[82674 rows x 3 columns]

In [239]:
### Lyft for time period 1 Dataframe sorted by time
Dict_Lyft1 = {'Distance':Lyft_00to06_distance,'Price':Lyft_00to06_price,'Time':Lyft_00to06}
df_Lyft1 = pd.DataFrame(Dict_Lyft1)
df_Lyft1 = df_Lyft1.sort_values('Distance').dropna()
df_Lyft1

       Distance  Price      Time
72907      0.39   13.5  05:43:03
243        0.39   10.5  00:00:11
68870      0.39    5.0  05:21:23
245        0.39    7.0  00:00:11
246        0.39    9.0  00:00:11
...         ...    ...       ...
71371      6.13   38.0  05:35:11
71373      6.13   11.0  05:35:11
71372      6.13   26.0  05:35:11
39250      6.33   16.5  02:55:13
15109      6.33   47.5  01:00:22

[75755 rows x 3 columns]

In [240]:
### Lyft for time period 2 Dataframe sorted by time
Dict_Lyft2 = {'Distance':Lyft_06to12_distance,'Price':Lyft_06to12_price,'Time':Lyft_06to12}
df_Lyft2 = pd.DataFrame(Dict_Lyft2)
df_Lyft2 = df_Lyft2.sort_values('Distance').dropna()
df_Lyft2

       Distance  Price      Time
50307      0.39   16.5  10:15:23
56194      0.39    7.0  10:43:00
23851      0.39   16.5  08:03:23
23850      0.39    7.0  08:03:23
49796      0.39   26.0  10:14:07
...         ...    ...       ...
54134      6.13   30.0  10:33:21
54136      6.13   47.5  10:33:21
33022      6.14   55.0  08:55:08
33020      6.14   32.5  08:55:08
33023      6.14   27.5  08:55:08

[73304 rows x 3 columns]

In [241]:
### Lyft for time period 3 Dataframe sorted by time
Dict_Lyft3 = {'Distance':Lyft_12to18_distance,'Price':Lyft_12to18_price,'Time':Lyft_12to18}
df_Lyft3 = pd.DataFrame(Dict_Lyft3)
df_Lyft3 = df_Lyft3.sort_values('Distance').dropna()
df_Lyft3

       Distance  Price      Time
64222      0.39   27.5  16:45:13
26073      0.39    9.0  13:55:03
26074      0.39   26.0  13:55:03
26075      0.39   16.5  13:55:03
59575      0.39   10.5  16:25:07
...         ...    ...       ...
78236      6.09   55.0  17:45:22
78235      6.09   16.5  17:45:22
23453      6.14   10.5  13:42:59
23452      6.14   16.5  13:42:59
23454      6.14   38.5  13:42:59

[81038 rows x 3 columns]

In [242]:
### Lyft for time period 4 Dataframe sorted by time
Dict_Lyft4 = {'Distance':Lyft_18to00_distance,'Price':Lyft_18to00_price,'Time':Lyft_18to00}
df_Lyft4 = pd.DataFrame(Dict_Lyft4)
df_Lyft4 = df_Lyft4.sort_values('Distance').dropna()
df_Lyft4

       Distance  Price      Time
60166      0.39   16.5  22:45:24
15315      0.39    7.0  19:07:59
27209      0.39    3.5  20:06:22
54277      0.39    9.0  22:20:03
54280      0.39   11.0  22:20:03
...         ...    ...       ...
14883      6.12   16.5  19:05:11
16096      6.33   42.5  19:10:13
20830      6.33   26.0  19:33:24
5761       6.33   30.0  18:25:09
8291       6.33   11.0  18:35:16

[77311 rows x 3 columns]

In [243]:
# For Lyft 1
idx_1 = [] #For distance 0 - 1 mile
idx_2 = [] #For distance 1 - 2 mile
idx_3 = [] #For distance 2 - 3 mile
idx_4 = [] #For distance 3 - 4 mile
idx_5 = [] #For distance 4 - 5 mile
idx_6 = [] #For distance 5 - 6 mile
idx_7 = [] #For distance 6 - 7 mile
idx_8 = [] #For distance 7 - 8 mile

L1 = np.mean(df_Lyft1['Price'])
for i in range(len(df_Lyft1)):
    if 0 <= df_Lyft1['Distance'][i] <= 1:
        idx_1.append(df_Lyft1['Price'][i])
    if 1 < df_Lyft1['Distance'][i] <= 2:
        idx_2.append(df_Lyft1['Price'][i])
    if 2 < df_Lyft1['Distance'][i] <= 3:
        idx_3.append(df_Lyft1['Price'][i])
    if 3 < df_Lyft1['Distance'][i] <= 4:
        idx_4.append(df_Lyft1['Price'][i])
    if 4 < df_Lyft1['Distance'][i] <= 5:
        idx_5.append(df_Lyft1['Price'][i])
    if 5 < df_Lyft1['Distance'][i] <= 6:
        idx_6.append(df_Lyft1['Price'][i])
    if 6 < df_Lyft1['Distance'][i] <= 7:
        idx_7.append(df_Lyft1['Price'][i])
    if 7 < df_Lyft1['Distance'][i] <= 8:
        idx_8.append(df_Lyft1['Price'][i])


# For Lyft 1
a1 = np.mean(idx_1)/L1
a2 = np.mean(idx_2)/L1
a3 = np.mean(idx_3)/L1
a4 = np.mean(idx_4)/L1
a5 = np.mean(idx_5)/L1
a6 = np.mean(idx_6)/L1
a7 = np.mean(idx_7)/L1
a8 = np.mean(idx_8)/L1

df_Lyft1['Index'] = 0.00
df_Lyft1['DPeriod'] = 0

In [244]:
# For Lyft 1
for i in range(len(df_Lyft1)):
    if 0 <= df_Lyft1['Distance'][i] <= 1:
        df_Lyft1['Index'][i] = a1
        df_Lyft1['DPeriod'][i] = 1        
    if 1 < df_Lyft1['Distance'][i] <= 2:
        df_Lyft1['Index'][i] = a2
        df_Lyft1['DPeriod'][i] = 2        
    if 2 < df_Lyft1['Distance'][i] <= 3:
        df_Lyft1['Index'][i] = a3
        df_Lyft1['DPeriod'][i] = 3        
    if 3 < df_Lyft1['Distance'][i] <= 4:
        df_Lyft1['Index'][i] = a4
        df_Lyft1['DPeriod'][i] = 4        
    if 4 < df_Lyft1['Distance'][i] <= 5:
        df_Lyft1['Index'][i] = a5
        df_Lyft1['DPeriod'][i] = 5        
    if 5 < df_Lyft1['Distance'][i] <= 6:
        df_Lyft1['Index'][i] = a6
        df_Lyft1['DPeriod'][i] = 6        
    if 6 < df_Lyft1['Distance'][i] <= 7:
        df_Lyft1['Index'][i] = a7
        df_Lyft1['DPeriod'][i] = 7        
    if 7 < df_Lyft1['Distance'][i] <= 8:
        df_Lyft1['Index'][i] = a8
        df_Lyft1['DPeriod'][i] = 8        
df_Lyft1

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

       Distance  Price      Time     Index  DPeriod
72907      0.39   13.5  05:43:03  0.742028        1
243        0.39   10.5  00:00:11  0.742028        1
68870      0.39    5.0  05:21:23  0.742028        1
245        0.39    7.0  00:00:11  0.742028        1
246        0.39    9.0  00:00:11  0.742028        1
...         ...    ...       ...       ...      ...
71371      6.13   38.0  05:35:11  1.968208        7
71373      6.13   11.0  05:35:11  1.968208        7
71372      6.13   26.0  05:35:11  1.968208        7
39250      6.33   16.5  02:55:13  1.968208        7
15109      6.33   47.5  01:00:22  1.968208        7

[75755 rows x 5 columns]

In [245]:
# For Lyft 2
idx_1 = [] #For distance 0 - 1 mile
idx_2 = [] #For distance 1 - 2 mile
idx_3 = [] #For distance 2 - 3 mile
idx_4 = [] #For distance 3 - 4 mile
idx_5 = [] #For distance 4 - 5 mile
idx_6 = [] #For distance 5 - 6 mile
idx_7 = [] #For distance 6 - 7 mile
idx_8 = [] #For distance 7 - 8 mile

L2 = np.mean(df_Lyft2['Price'])
for i in range(len(df_Lyft2)):
    if 0 <= df_Lyft2['Distance'][i] <= 1:
        idx_1.append(df_Lyft2['Price'][i])
    if 1 < df_Lyft2['Distance'][i] <= 2:
        idx_2.append(df_Lyft2['Price'][i])
    if 2 < df_Lyft2['Distance'][i] <= 3:
        idx_3.append(df_Lyft2['Price'][i])
    if 3 < df_Lyft2['Distance'][i] <= 4:
        idx_4.append(df_Lyft2['Price'][i])
    if 4 < df_Lyft2['Distance'][i] <= 5:
        idx_5.append(df_Lyft2['Price'][i])
    if 5 < df_Lyft2['Distance'][i] <= 6:
        idx_6.append(df_Lyft2['Price'][i])
    if 6 < df_Lyft2['Distance'][i] <= 7:
        idx_7.append(df_Lyft2['Price'][i])
    if 7 < df_Lyft2['Distance'][i] <= 8:
        idx_8.append(df_Lyft2['Price'][i])


# For Lyft 2
a1 = np.mean(idx_1)/L2
a2 = np.mean(idx_2)/L2
a3 = np.mean(idx_3)/L2
a4 = np.mean(idx_4)/L2
a5 = np.mean(idx_5)/L2
a6 = np.mean(idx_6)/L2
a7 = np.mean(idx_7)/L2
a8 = np.mean(idx_8)/L2
df_Lyft2['Index'] = 0.00
df_Lyft2['DPeriod'] = 0

In [246]:
# For Lyft 2
for i in range(len(df_Lyft2)):
    if 0 <= df_Lyft2['Distance'][i] <= 1:
        df_Lyft2['Index'][i] = a1
        df_Lyft2['DPeriod'][i] = 1        
    if 1 < df_Lyft2['Distance'][i] <= 2:
        df_Lyft2['Index'][i] = a2
        df_Lyft2['DPeriod'][i] = 2        
    if 2 < df_Lyft2['Distance'][i] <= 3:
        df_Lyft2['Index'][i] = a3
        df_Lyft2['DPeriod'][i] = 3        
    if 3 < df_Lyft2['Distance'][i] <= 4:
        df_Lyft2['Index'][i] = a4
        df_Lyft2['DPeriod'][i] = 4        
    if 4 < df_Lyft2['Distance'][i] <= 5:
        df_Lyft2['Index'][i] = a5
        df_Lyft2['DPeriod'][i] = 5        
    if 5 < df_Lyft2['Distance'][i] <= 6:
        df_Lyft2['Index'][i] = a6
        df_Lyft2['DPeriod'][i] = 6        
    if 6 < df_Lyft2['Distance'][i] <= 7:
        df_Lyft2['Index'][i] = a7
        df_Lyft2['DPeriod'][i] = 7        
    if 7 < df_Lyft2['Distance'][i] <= 8:
        df_Lyft2['Index'][i] = a8
        df_Lyft2['DPeriod'][i] = 8        
df_Lyft2

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

       Distance  Price      Time     Index  DPeriod
50307      0.39   16.5  10:15:23  0.735064        1
56194      0.39    7.0  10:43:00  0.735064        1
23851      0.39   16.5  08:03:23  0.735064        1
23850      0.39    7.0  08:03:23  0.735064        1
49796      0.39   26.0  10:14:07  0.735064        1
...         ...    ...       ...       ...      ...
54134      6.13   30.0  10:33:21  1.873650        7
54136      6.13   47.5  10:33:21  1.873650        7
33022      6.14   55.0  08:55:08  1.873650        7
33020      6.14   32.5  08:55:08  1.873650        7
33023      6.14   27.5  08:55:08  1.873650        7

[73304 rows x 5 columns]

In [247]:
# For Lyft 3
idx_1 = [] #For distance 0 - 1 mile
idx_2 = [] #For distance 1 - 2 mile
idx_3 = [] #For distance 2 - 3 mile
idx_4 = [] #For distance 3 - 4 mile
idx_5 = [] #For distance 4 - 5 mile
idx_6 = [] #For distance 5 - 6 mile
idx_7 = [] #For distance 6 - 7 mile
idx_8 = [] #For distance 7 - 8 mile

L3 = np.mean(df_Lyft3['Price'])
for i in range(len(df_Lyft3)):
    if 0 <= df_Lyft3['Distance'][i] <= 1:
        idx_1.append(df_Lyft3['Price'][i])
    if 1 < df_Lyft3['Distance'][i] <= 2:
        idx_2.append(df_Lyft3['Price'][i])
    if 2 < df_Lyft3['Distance'][i] <= 3:
        idx_3.append(df_Lyft3['Price'][i])
    if 3 < df_Lyft3['Distance'][i] <= 4:
        idx_4.append(df_Lyft3['Price'][i])
    if 4 < df_Lyft3['Distance'][i] <= 5:
        idx_5.append(df_Lyft3['Price'][i])
    if 5 < df_Lyft3['Distance'][i] <= 6:
        idx_6.append(df_Lyft3['Price'][i])
    if 6 < df_Lyft3['Distance'][i] <= 7:
        idx_7.append(df_Lyft3['Price'][i])
    if 7 < df_Lyft3['Distance'][i] <= 8:
        idx_8.append(df_Lyft3['Price'][i])


# For Lyft 3
a1 = np.mean(idx_1)/L3
a2 = np.mean(idx_2)/L3
a3 = np.mean(idx_3)/L3
a4 = np.mean(idx_4)/L3
a5 = np.mean(idx_5)/L3
a6 = np.mean(idx_6)/L3
a7 = np.mean(idx_7)/L3
a8 = np.mean(idx_8)/L3
df_Lyft3['Index'] = 0.00
df_Lyft3['DPeriod'] = 0

In [248]:
# For Lyft 3
for i in range(len(df_Lyft3)):
    if 0 <= df_Lyft3['Distance'][i] <= 1:
        df_Lyft3['Index'][i] = a1
        df_Lyft3['DPeriod'][i] = 1        
    if 1 < df_Lyft3['Distance'][i] <= 2:
        df_Lyft3['Index'][i] = a2
        df_Lyft3['DPeriod'][i] = 2        
    if 2 < df_Lyft3['Distance'][i] <= 3:
        df_Lyft3['Index'][i] = a3
        df_Lyft3['DPeriod'][i] = 3        
    if 3 < df_Lyft3['Distance'][i] <= 4:
        df_Lyft3['Index'][i] = a4
        df_Lyft3['DPeriod'][i] = 4        
    if 4 < df_Lyft3['Distance'][i] <= 5:
        df_Lyft3['Index'][i] = a5
        df_Lyft3['DPeriod'][i] = 5        
    if 5 < df_Lyft3['Distance'][i] <= 6:
        df_Lyft3['Index'][i] = a6
        df_Lyft3['DPeriod'][i] = 6        
    if 6 < df_Lyft3['Distance'][i] <= 7:
        df_Lyft3['Index'][i] = a7
        df_Lyft3['DPeriod'][i] = 7        
    if 7 < df_Lyft3['Distance'][i] <= 8:
        df_Lyft3['Index'][i] = a8
        df_Lyft3['DPeriod'][i] = 8        
df_Lyft3

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

       Distance  Price      Time     Index  DPeriod
64222      0.39   27.5  16:45:13  0.743900        1
26073      0.39    9.0  13:55:03  0.743900        1
26074      0.39   26.0  13:55:03  0.743900        1
26075      0.39   16.5  13:55:03  0.743900        1
59575      0.39   10.5  16:25:07  0.743900        1
...         ...    ...       ...       ...      ...
78236      6.09   55.0  17:45:22  1.600118        7
78235      6.09   16.5  17:45:22  1.600118        7
23453      6.14   10.5  13:42:59  1.600118        7
23452      6.14   16.5  13:42:59  1.600118        7
23454      6.14   38.5  13:42:59  1.600118        7

[81038 rows x 5 columns]

In [249]:
# For Lyft 4
idx_1 = [] #For distance 0 - 1 mile
idx_2 = [] #For distance 1 - 2 mile
idx_3 = [] #For distance 2 - 3 mile
idx_4 = [] #For distance 3 - 4 mile
idx_5 = [] #For distance 4 - 5 mile
idx_6 = [] #For distance 5 - 6 mile
idx_7 = [] #For distance 6 - 7 mile
idx_8 = [] #For distance 7 - 8 mile

L4 = np.mean(df_Lyft4['Price'])
for i in range(len(df_Lyft4)):
    if 0 <= df_Lyft4['Distance'][i] <= 1:
        idx_1.append(df_Lyft4['Price'][i])
    if 1 < df_Lyft4['Distance'][i] <= 2:
        idx_2.append(df_Lyft4['Price'][i])
    if 2 < df_Lyft4['Distance'][i] <= 3:
        idx_3.append(df_Lyft4['Price'][i])
    if 3 < df_Lyft4['Distance'][i] <= 4:
        idx_4.append(df_Lyft4['Price'][i])
    if 4 < df_Lyft4['Distance'][i] <= 5:
        idx_5.append(df_Lyft4['Price'][i])
    if 5 < df_Lyft4['Distance'][i] <= 6:
        idx_6.append(df_Lyft4['Price'][i])
    if 6 < df_Lyft4['Distance'][i] <= 7:
        idx_7.append(df_Lyft4['Price'][i])
    if 7 < df_Lyft4['Distance'][i] <= 8:
        idx_8.append(df_Lyft4['Price'][i])


# For Lyft 4
a1 = np.mean(idx_1)/L4
a2 = np.mean(idx_2)/L4
a3 = np.mean(idx_3)/L4
a4 = np.mean(idx_4)/L4
a5 = np.mean(idx_5)/L4
a6 = np.mean(idx_6)/L4
a7 = np.mean(idx_7)/L4
a8 = np.mean(idx_8)/L4
df_Lyft4['Index'] = 0.00
df_Lyft4['DPeriod'] = 0

In [250]:
# For Lyft 4
for i in range(len(df_Lyft4)):
    if 0 <= df_Lyft4['Distance'][i] <= 1:
        df_Lyft4['Index'][i] = a1
        df_Lyft4['DPeriod'][i] = 1        
    if 1 < df_Lyft4['Distance'][i] <= 2:
        df_Lyft4['Index'][i] = a2
        df_Lyft4['DPeriod'][i] = 2        
    if 2 < df_Lyft4['Distance'][i] <= 3:
        df_Lyft4['Index'][i] = a3
        df_Lyft4['DPeriod'][i] = 3        
    if 3 < df_Lyft4['Distance'][i] <= 4:
        df_Lyft4['Index'][i] = a4
        df_Lyft4['DPeriod'][i] = 4        
    if 4 < df_Lyft4['Distance'][i] <= 5:
        df_Lyft4['Index'][i] = a5
        df_Lyft4['DPeriod'][i] = 5        
    if 5 < df_Lyft4['Distance'][i] <= 6:
        df_Lyft4['Index'][i] = a6
        df_Lyft4['DPeriod'][i] = 6        
    if 6 < df_Lyft4['Distance'][i] <= 7:
        df_Lyft4['Index'][i] = a7
        df_Lyft4['DPeriod'][i] = 7        
    if 7 < df_Lyft4['Distance'][i] <= 8:
        df_Lyft4['Index'][i] = a8
        df_Lyft4['DPeriod'][i] = 8        
df_Lyft4

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

       Distance  Price      Time     Index  DPeriod
60166      0.39   16.5  22:45:24  0.728279        1
15315      0.39    7.0  19:07:59  0.728279        1
27209      0.39    3.5  20:06:22  0.728279        1
54277      0.39    9.0  22:20:03  0.728279        1
54280      0.39   11.0  22:20:03  0.728279        1
...         ...    ...       ...       ...      ...
14883      6.12   16.5  19:05:11  1.448824        7
16096      6.33   42.5  19:10:13  1.448824        7
20830      6.33   26.0  19:33:24  1.448824        7
5761       6.33   30.0  18:25:09  1.448824        7
8291       6.33   11.0  18:35:16  1.448824        7

[77311 rows x 5 columns]

In [251]:
# For Uber 1
idx_1 = [] #For distance 0 - 1 mile
idx_2 = [] #For distance 1 - 2 mile
idx_3 = [] #For distance 2 - 3 mile
idx_4 = [] #For distance 3 - 4 mile
idx_5 = [] #For distance 4 - 5 mile
idx_6 = [] #For distance 5 - 6 mile
idx_7 = [] #For distance 6 - 7 mile
idx_8 = [] #For distance 7 - 8 mile

U1 = np.mean(df_Uber1['Price'])
for i in range(len(df_Uber1)):
    if 0 <= df_Uber1['Distance'][i] <= 1:
        idx_1.append(df_Uber1['Price'][i])
    if 1 < df_Uber1['Distance'][i] <= 2:
        idx_2.append(df_Uber1['Price'][i])
    if 2 < df_Uber1['Distance'][i] <= 3:
        idx_3.append(df_Uber1['Price'][i])
    if 3 < df_Uber1['Distance'][i] <= 4:
        idx_4.append(df_Uber1['Price'][i])
    if 4 < df_Uber1['Distance'][i] <= 5:
        idx_5.append(df_Uber1['Price'][i])
    if 5 < df_Uber1['Distance'][i] <= 6:
        idx_6.append(df_Uber1['Price'][i])
    if 6 < df_Uber1['Distance'][i] <= 7:
        idx_7.append(df_Uber1['Price'][i])
    if 7 < df_Uber1['Distance'][i] <= 8:
        idx_8.append(df_Uber1['Price'][i])


# For Uber 1
a1 = np.mean(idx_1)/U1
a2 = np.mean(idx_2)/U1
a3 = np.mean(idx_3)/U1
a4 = np.mean(idx_4)/U1
a5 = np.mean(idx_5)/U1
a6 = np.mean(idx_6)/U1
a7 = np.mean(idx_7)/U1
a8 = np.mean(idx_8)/U1
df_Uber1['Index'] = 0.00
df_Uber1['DPeriod'] = 0

In [252]:
# For Uber 1
for i in range(len(df_Uber1)):
    if 0 <= df_Uber1['Distance'][i] <= 1:
        df_Uber1['Index'][i] = a1
        df_Uber1['DPeriod'][i] = 1        
    if 1 < df_Uber1['Distance'][i] <= 2:
        df_Uber1['Index'][i] = a2
        df_Uber1['DPeriod'][i] = 2        
    if 2 < df_Uber1['Distance'][i] <= 3:
        df_Uber1['Index'][i] = a3
        df_Uber1['DPeriod'][i] = 3        
    if 3 < df_Uber1['Distance'][i] <= 4:
        df_Uber1['Index'][i] = a4
        df_Uber1['DPeriod'][i] = 4        
    if 4 < df_Uber1['Distance'][i] <= 5:
        df_Uber1['Index'][i] = a5
        df_Uber1['DPeriod'][i] = 5        
    if 5 < df_Uber1['Distance'][i] <= 6:
        df_Uber1['Index'][i] = a6
        df_Uber1['DPeriod'][i] = 6        
    if 6 < df_Uber1['Distance'][i] <= 7:
        df_Uber1['Index'][i] = a7
        df_Uber1['DPeriod'][i] = 7        
    if 7 < df_Uber1['Distance'][i] <= 8:
        df_Uber1['Index'][i] = a8
        df_Uber1['DPeriod'][i] = 8        
df_Uber1

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

       Distance  Price      Time     Index  DPeriod
21806      0.02    6.5  01:27:22  0.794071        1
5910       0.02    8.5  00:23:04  0.794071        1
25100      0.02    7.5  01:42:57  0.794071        1
5908       0.02    6.5  00:23:04  0.794071        1
62154      0.02    6.5  04:25:13  0.794071        1
...         ...    ...       ...       ...      ...
475        7.50   16.5  00:00:22  1.714768        8
70724      7.86   29.5  05:05:06  1.714768        8
70721      7.86   53.0  05:05:06  1.714768        8
70722      7.86   13.5  05:05:06  1.714768        8
70723      7.86   17.5  05:05:06  1.714768        8

[81400 rows x 5 columns]

In [253]:
# For Uber 2
idx_1 = [] #For distance 0 - 1 mile
idx_2 = [] #For distance 1 - 2 mile
idx_3 = [] #For distance 2 - 3 mile
idx_4 = [] #For distance 3 - 4 mile
idx_5 = [] #For distance 4 - 5 mile
idx_6 = [] #For distance 5 - 6 mile
idx_7 = [] #For distance 6 - 7 mile
idx_8 = [] #For distance 7 - 8 mile

U2 = np.mean(df_Uber2['Price'])
for i in range(len(df_Uber2)):
    if 0 <= df_Uber2['Distance'][i] <= 1:
        idx_1.append(df_Uber2['Price'][i])
    if 1 < df_Uber2['Distance'][i] <= 2:
        idx_2.append(df_Uber2['Price'][i])
    if 2 < df_Uber2['Distance'][i] <= 3:
        idx_3.append(df_Uber2['Price'][i])
    if 3 < df_Uber2['Distance'][i] <= 4:
        idx_4.append(df_Uber2['Price'][i])
    if 4 < df_Uber2['Distance'][i] <= 5:
        idx_5.append(df_Uber2['Price'][i])
    if 5 < df_Uber2['Distance'][i] <= 6:
        idx_6.append(df_Uber2['Price'][i])
    if 6 < df_Uber2['Distance'][i] <= 7:
        idx_7.append(df_Uber2['Price'][i])
    if 7 < df_Uber2['Distance'][i] <= 8:
        idx_8.append(df_Uber2['Price'][i])


# For Uber 2
a1 = np.mean(idx_1)/U2
a2 = np.mean(idx_2)/U2
a3 = np.mean(idx_3)/U2
a4 = np.mean(idx_4)/U2
a5 = np.mean(idx_5)/U2
a6 = np.mean(idx_6)/U2
a7 = np.mean(idx_7)/U2
a8 = np.mean(idx_8)/U2
df_Uber2['Index'] = 0.00
df_Uber2['DPeriod'] = 0

In [254]:
# For Uber 2
for i in range(len(df_Uber2)):
    if 0 <= df_Uber2['Distance'][i] <= 1:
        df_Uber2['Index'][i] = a1
        df_Uber2['DPeriod'][i] = 1        
    if 1 < df_Uber2['Distance'][i] <= 2:
        df_Uber2['Index'][i] = a2
        df_Uber2['DPeriod'][i] = 2        
    if 2 < df_Uber2['Distance'][i] <= 3:
        df_Uber2['Index'][i] = a3
        df_Uber2['DPeriod'][i] = 3        
    if 3 < df_Uber2['Distance'][i] <= 4:
        df_Uber2['Index'][i] = a4
        df_Uber2['DPeriod'][i] = 4        
    if 4 < df_Uber2['Distance'][i] <= 5:
        df_Uber2['Index'][i] = a5
        df_Uber2['DPeriod'][i] = 5        
    if 5 < df_Uber2['Distance'][i] <= 6:
        df_Uber2['Index'][i] = a6
        df_Uber2['DPeriod'][i] = 6        
    if 6 < df_Uber2['Distance'][i] <= 7:
        df_Uber2['Index'][i] = a7
        df_Uber2['DPeriod'][i] = 7        
    if 7 < df_Uber2['Distance'][i] <= 8:
        df_Uber2['Index'][i] = a8
        df_Uber2['DPeriod'][i] = 8        
df_Uber2

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

       Distance  Price      Time     Index  DPeriod
78389      0.02    7.5  11:54:22  0.790487        1
56542      0.02    6.5  10:23:07  0.790487        1
78388      0.02    9.5  11:54:22  0.790487        1
11194      0.02    6.5  06:49:50  0.790487        1
56541      0.02   15.0  10:23:07  0.790487        1
...         ...    ...       ...       ...      ...
19871      7.50   14.5  07:33:00  1.743235        8
69147      7.50   46.0  11:15:22  1.743235        8
57680      7.50   31.5  10:28:02  1.743235        8
27617      7.50   16.5  08:12:21  1.743235        8
27619      7.50   26.0  08:12:21  1.743235        8

[79647 rows x 5 columns]

In [255]:
# For Uber 3
idx_1 = [] #For distance 0 - 1 mile
idx_2 = [] #For distance 1 - 2 mile
idx_3 = [] #For distance 2 - 3 mile
idx_4 = [] #For distance 3 - 4 mile
idx_5 = [] #For distance 4 - 5 mile
idx_6 = [] #For distance 5 - 6 mile
idx_7 = [] #For distance 6 - 7 mile
idx_8 = [] #For distance 7 - 8 mile

U3 = np.mean(df_Uber3['Price'])
for i in range(len(df_Uber3)):
    if 0 <= df_Uber3['Distance'][i] <= 1:
        idx_1.append(df_Uber3['Price'][i])
    if 1 < df_Uber3['Distance'][i] <= 2:
        idx_2.append(df_Uber3['Price'][i])
    if 2 < df_Uber3['Distance'][i] <= 3:
        idx_3.append(df_Uber3['Price'][i])
    if 3 < df_Uber3['Distance'][i] <= 4:
        idx_4.append(df_Uber3['Price'][i])
    if 4 < df_Uber3['Distance'][i] <= 5:
        idx_5.append(df_Uber3['Price'][i])
    if 5 < df_Uber3['Distance'][i] <= 6:
        idx_6.append(df_Uber3['Price'][i])
    if 6 < df_Uber3['Distance'][i] <= 7:
        idx_7.append(df_Uber3['Price'][i])
    if 7 < df_Uber3['Distance'][i] <= 8:
        idx_8.append(df_Uber3['Price'][i])


# For Uber 3
a1 = np.mean(idx_1)/U3
a2 = np.mean(idx_2)/U3
a3 = np.mean(idx_3)/U3
a4 = np.mean(idx_4)/U3
a5 = np.mean(idx_5)/U3
a6 = np.mean(idx_6)/U3
a7 = np.mean(idx_7)/U3
a8 = np.mean(idx_8)/U3
df_Uber3['Index'] = 0.00
df_Uber3['DPeriod'] = 0

In [256]:
# For Uber 3
for i in range(len(df_Uber3)):
    if 0 <= df_Uber3['Distance'][i] <= 1:
        df_Uber3['Index'][i] = a1
        df_Uber3['DPeriod'][i] = 1        
    if 1 < df_Uber3['Distance'][i] <= 2:
        df_Uber3['Index'][i] = a2
        df_Uber3['DPeriod'][i] = 2
    if 2 < df_Uber3['Distance'][i] <= 3:
        df_Uber3['Index'][i] = a3
        df_Uber3['DPeriod'][i] = 3
    if 3 < df_Uber3['Distance'][i] <= 4:
        df_Uber3['Index'][i] = a4
        df_Uber3['DPeriod'][i] = 4
    if 4 < df_Uber3['Distance'][i] <= 5:
        df_Uber3['Index'][i] = a5
        df_Uber3['DPeriod'][i] = 5
    if 5 < df_Uber3['Distance'][i] <= 6:
        df_Uber3['Index'][i] = a6
        df_Uber3['DPeriod'][i] = 6
    if 6 < df_Uber3['Distance'][i] <= 7:
        df_Uber3['Index'][i] = a7
        df_Uber3['DPeriod'][i] = 7
    if 7 < df_Uber3['Distance'][i] <= 8:
        df_Uber3['Index'][i] = a8
        df_Uber3['DPeriod'][i] = 8
df_Uber3

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

       Distance  Price      Time     Index  DPeriod
64476      0.02   15.0  16:25:11  0.788528        1
37532      0.02    8.5  14:35:07  0.788528        1
39589      0.02   27.5  14:43:03  0.788528        1
702        0.02   27.5  12:02:11  0.788528        1
64475      0.02    6.5  16:25:11  0.788528        1
...         ...    ...       ...       ...      ...
19396      7.62   17.0  13:20:06  1.748627        8
28176      7.62   13.5  13:56:08  1.748627        8
19397      7.62   28.5  13:20:06  1.748627        8
60682      7.86   17.5  16:10:10  1.748627        8
60681      7.86   36.0  16:10:10  1.748627        8

[86847 rows x 5 columns]

In [257]:
# For Uber 4
idx_1 = [] #For distance 0 - 1 mile
idx_2 = [] #For distance 1 - 2 mile
idx_3 = [] #For distance 2 - 3 mile
idx_4 = [] #For distance 3 - 4 mile
idx_5 = [] #For distance 4 - 5 mile
idx_6 = [] #For distance 5 - 6 mile
idx_7 = [] #For distance 6 - 7 mile
idx_8 = [] #For distance 7 - 8 mile

U4 = np.mean(df_Uber4['Price'])
for i in range(len(df_Uber4)):
    if 0 <= df_Uber4['Distance'][i] <= 1:
        idx_1.append(df_Uber4['Price'][i])
    if 1 < df_Uber4['Distance'][i] <= 2:
        idx_2.append(df_Uber4['Price'][i])
    if 2 < df_Uber4['Distance'][i] <= 3:
        idx_3.append(df_Uber4['Price'][i])
    if 3 < df_Uber4['Distance'][i] <= 4:
        idx_4.append(df_Uber4['Price'][i])
    if 4 < df_Uber4['Distance'][i] <= 5:
        idx_5.append(df_Uber4['Price'][i])
    if 5 < df_Uber4['Distance'][i] <= 6:
        idx_6.append(df_Uber4['Price'][i])
    if 6 < df_Uber4['Distance'][i] <= 7:
        idx_7.append(df_Uber4['Price'][i])
    if 7 < df_Uber4['Distance'][i] <= 8:
        idx_8.append(df_Uber4['Price'][i])


# For Uber 4
a1 = np.mean(idx_1)/U4
a2 = np.mean(idx_2)/U4
a3 = np.mean(idx_3)/U4
a4 = np.mean(idx_4)/U4
a5 = np.mean(idx_5)/U4
a6 = np.mean(idx_6)/U4
a7 = np.mean(idx_7)/U4
a8 = np.mean(idx_8)/U4
df_Uber4['Index'] = 0.00
df_Uber4['DPeriod'] = 0

In [258]:
# For Uber 4
for i in range(len(df_Uber4)):
    if 0 <= df_Uber4['Distance'][i] <= 1:
        df_Uber4['Index'][i] = a1
        df_Uber4['DPeriod'][i] = 1
    if 1 < df_Uber4['Distance'][i] <= 2:
        df_Uber4['Index'][i] = a2
        df_Uber4['DPeriod'][i] = 2
    if 2 < df_Uber4['Distance'][i] <= 3:
        df_Uber4['Index'][i] = a3
        df_Uber4['DPeriod'][i] = 3
    if 3 < df_Uber4['Distance'][i] <= 4:
        df_Uber4['Index'][i] = a4
        df_Uber4['DPeriod'][i] = 4
    if 4 < df_Uber4['Distance'][i] <= 5:
        df_Uber4['Index'][i] = a5
        df_Uber4['DPeriod'][i] = 5
    if 5 < df_Uber4['Distance'][i] <= 6:
        df_Uber4['Index'][i] = a6
        df_Uber4['DPeriod'][i] = 6
    if 6 < df_Uber4['Distance'][i] <= 7:
        df_Uber4['Index'][i] = a7
        df_Uber4['DPeriod'][i] = 7
    if 7 < df_Uber4['Distance'][i] <= 8:
        df_Uber4['Index'][i] = a8
        df_Uber4['DPeriod'][i] = 8
df_Uber4

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\Vishesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

       Distance  Price      Time     Index  DPeriod
56631      0.02    6.5  22:13:07  0.785492        1
52893      0.02   27.5  21:56:10  0.785492        1
52892      0.02    8.5  21:56:10  0.785492        1
72269      0.02   27.5  23:18:27  0.785492        1
9205       0.02   15.0  18:37:57  0.785492        1
...         ...    ...       ...       ...      ...
62483      7.46   54.0  22:40:03  1.778310        8
23310      7.46   16.0  19:39:23  1.778310        8
47061      7.46   16.0  21:30:10  1.778310        8
23292      7.46   13.0  19:39:22  1.778310        8
46322      7.50   18.5  21:27:24  1.778310        8

[82674 rows x 5 columns]